backend:
  name: git-gateway
  branch: main

media_folder: static/images/uploads
public_folder: /images

collections: 
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Post Image", name: "image", widget: "image"}
      - { label: "Body", name: "body", widget: "markdown" }

